
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jun 10 13:19:39 BRT 2023
//----------------------------------------------------

package AnalisadorSintatico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BUSCAR = 27;
  public static final int FECHA_COLCHETES = 13;
  public static final int EXTRAIR = 31;
  public static final int COMPILADORES = 24;
  public static final int DE = 32;
  public static final int POR = 30;
  public static final int OP_ARITIMETICOS = 22;
  public static final int SUBSTITUIR = 29;
  public static final int ERRO = 37;
  public static final int FIM = 26;
  public static final int ATE = 33;
  public static final int TIPO_VAR = 2;
  public static final int OP_INCREMENTO = 19;
  public static final int COMPARAR = 36;
  public static final int COND_SENAO = 7;
  public static final int OP_RELACIONAL = 20;
  public static final int EOF = 0;
  public static final int PONTO_VIRGULA = 11;
  public static final int ABRE_PARENTESES = 16;
  public static final int error = 1;
  public static final int ENQUANTO = 10;
  public static final int COMPRIMENTO = 34;
  public static final int VAL_INTEIRO = 5;
  public static final int CONCATENAR = 35;
  public static final int EM = 28;
  public static final int COND_SE = 8;
  public static final int ABRE_COLCHETES = 12;
  public static final int OP_LOGICO = 18;
  public static final int FECHA_PARENTESES = 17;
  public static final int OP_ATRIBUICAO = 21;
  public static final int VAL_BOOLEANO = 6;
  public static final int IFSULDEMINAS = 23;
  public static final int VAL_TEXTO = 4;
  public static final int ABRE_CHAVES = 14;
  public static final int PARA = 9;
  public static final int INICIO = 25;
  public static final int FECHA_CHAVES = 15;
  public static final int VAR = 3;
}

