package analizadorLexico;

/* The following code was generated by JFlex 1.4.3 on 21/04/2023 00:36 */

import static analizadorLexico.Tokens.*;
import java_cup.runtime.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 21/04/2023 00:36 from the specification file
 * <tt>C:/Users/fabri/Desktop/com/Compilador/AnalisadorLexico/AnalisadorLexico/src/analizadorLexico/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\5\1\4\25\0\1\5\1\63\1\30\1\3\1\0\1\27"+
    "\2\0\1\36\1\37\1\27\1\25\1\0\1\26\2\0\12\2\1\0"+
    "\1\31\1\64\1\40\1\64\2\0\1\60\1\1\1\44\1\56\1\57"+
    "\1\46\2\1\1\42\2\1\1\55\1\47\1\43\1\45\1\61\1\1"+
    "\1\62\1\53\1\1\1\54\5\1\1\32\1\0\1\33\1\0\1\1"+
    "\1\0\1\16\1\14\1\50\1\22\1\11\1\23\2\1\1\51\2\1"+
    "\1\15\1\10\1\6\1\13\1\41\1\52\1\12\1\24\1\17\1\7"+
    "\1\21\1\1\1\20\2\1\1\34\1\0\1\35\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\1\5\1\2"+
    "\1\6\10\2\3\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\5\2\1\1\1\21\1\0"+
    "\1\22\2\2\1\23\1\2\1\6\5\2\1\24\2\2"+
    "\1\25\1\26\1\0\1\27\1\0\1\21\14\2\1\30"+
    "\5\2\1\0\1\31\4\2\1\32\14\2\1\3\1\33"+
    "\11\2\1\34\1\2\1\35\1\2\1\36\10\2\1\37"+
    "\3\2\1\40\6\2\1\41\6\2\1\42\5\2\1\43"+
    "\5\2\1\44\2\2\1\45\3\2\1\46\1\47\1\50";

  private static int [] zzUnpackAction() {
    int [] result = new int[158];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\152\0\237\0\324\0\65\0\u0109\0\u013e"+
    "\0\u0173\0\u01a8\0\u01dd\0\u0212\0\u0247\0\u027c\0\u02b1\0\u02e6"+
    "\0\u031b\0\u0350\0\u0385\0\65\0\u03ba\0\65\0\65\0\65"+
    "\0\65\0\65\0\u03ef\0\65\0\u0424\0\u0459\0\u048e\0\u04c3"+
    "\0\u04f8\0\u052d\0\u0424\0\u0424\0\324\0\324\0\u0562\0\u0597"+
    "\0\152\0\u05cc\0\152\0\u0601\0\u0636\0\u066b\0\u06a0\0\u06d5"+
    "\0\152\0\u070a\0\u073f\0\u0774\0\65\0\u03ba\0\65\0\u07a9"+
    "\0\65\0\u07de\0\u0813\0\u0848\0\u087d\0\u08b2\0\u08e7\0\u091c"+
    "\0\u0951\0\u0986\0\u09bb\0\u09f0\0\u0a25\0\152\0\u0a5a\0\u0a8f"+
    "\0\u0ac4\0\u0af9\0\u0b2e\0\u0b63\0\152\0\u0b98\0\u0bcd\0\u0c02"+
    "\0\u0c37\0\152\0\u0c6c\0\u0ca1\0\u0cd6\0\u0d0b\0\u0d40\0\u0d75"+
    "\0\u0daa\0\u0ddf\0\u0e14\0\u0e49\0\u0e7e\0\u0eb3\0\65\0\152"+
    "\0\u0ee8\0\u0f1d\0\u0f52\0\u0f87\0\u0fbc\0\u0ff1\0\u1026\0\u105b"+
    "\0\u1090\0\152\0\u10c5\0\152\0\u10fa\0\152\0\u112f\0\u1164"+
    "\0\u1199\0\u11ce\0\u1203\0\u1238\0\u126d\0\u12a2\0\152\0\u12d7"+
    "\0\u130c\0\u1341\0\152\0\u1376\0\u13ab\0\u13e0\0\u1415\0\u144a"+
    "\0\u147f\0\152\0\u14b4\0\u14e9\0\u151e\0\u1553\0\u1588\0\u15bd"+
    "\0\152\0\u15f2\0\u1627\0\u165c\0\u1691\0\u16c6\0\152\0\u16fb"+
    "\0\u1730\0\u1765\0\u179a\0\u17cf\0\152\0\u1804\0\u1839\0\152"+
    "\0\u186e\0\u18a3\0\u18d8\0\152\0\152\0\152";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[158];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\2\3"+
    "\1\11\1\3\1\12\1\13\1\3\1\14\1\15\1\3"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\3\1\40\1\3\1\41\1\3\1\42"+
    "\12\3\1\43\1\44\66\0\2\3\3\0\17\3\14\0"+
    "\22\3\4\0\1\4\62\0\3\45\1\46\61\45\5\0"+
    "\1\7\60\0\2\3\3\0\1\3\1\47\15\3\14\0"+
    "\22\3\3\0\2\3\3\0\1\50\1\3\1\51\7\3"+
    "\1\52\4\3\14\0\22\3\3\0\2\3\3\0\1\3"+
    "\1\53\15\3\14\0\22\3\3\0\2\3\3\0\1\3"+
    "\1\54\3\3\1\55\11\3\14\0\22\3\3\0\2\3"+
    "\3\0\11\3\1\56\5\3\14\0\22\3\3\0\2\3"+
    "\3\0\3\3\1\57\13\3\14\0\22\3\3\0\2\3"+
    "\3\0\3\3\1\60\13\3\14\0\22\3\3\0\2\3"+
    "\3\0\3\3\1\61\13\3\14\0\22\3\3\0\2\3"+
    "\3\0\10\3\1\62\6\3\14\0\22\3\3\0\2\3"+
    "\3\0\1\3\1\63\1\3\1\64\13\3\14\0\22\3"+
    "\27\0\1\65\65\0\1\65\36\0\30\66\1\67\34\66"+
    "\26\0\1\70\76\0\1\71\25\0\2\3\3\0\5\3"+
    "\1\72\2\3\1\73\6\3\14\0\22\3\3\0\2\3"+
    "\3\0\17\3\14\0\2\3\1\74\2\3\1\75\14\3"+
    "\3\0\2\3\3\0\17\3\14\0\4\3\1\76\15\3"+
    "\3\0\2\3\3\0\17\3\14\0\1\3\1\77\20\3"+
    "\3\0\2\3\3\0\5\3\1\100\11\3\14\0\22\3"+
    "\3\0\2\3\3\0\2\3\1\101\14\3\14\0\22\3"+
    "\3\0\2\3\3\0\17\3\14\0\11\3\1\102\10\3"+
    "\3\0\2\3\3\0\11\3\1\103\5\3\14\0\22\3"+
    "\3\0\2\3\3\0\16\3\1\104\14\0\22\3\3\0"+
    "\2\3\3\0\5\3\1\105\11\3\14\0\22\3\3\0"+
    "\2\3\3\0\3\3\1\106\13\3\14\0\22\3\3\0"+
    "\2\3\3\0\12\3\1\107\4\3\14\0\22\3\3\0"+
    "\2\3\3\0\4\3\1\110\12\3\14\0\22\3\3\0"+
    "\2\3\3\0\7\3\1\111\7\3\14\0\22\3\3\0"+
    "\2\3\3\0\6\3\1\112\10\3\14\0\22\3\3\0"+
    "\2\3\3\0\1\113\16\3\14\0\22\3\4\0\1\114"+
    "\63\0\2\3\3\0\4\3\1\115\12\3\14\0\22\3"+
    "\3\0\2\3\3\0\4\3\1\116\12\3\14\0\22\3"+
    "\3\0\2\3\3\0\17\3\14\0\1\3\1\117\20\3"+
    "\3\0\2\3\3\0\17\3\14\0\12\3\1\120\7\3"+
    "\3\0\2\3\3\0\17\3\14\0\6\3\1\121\13\3"+
    "\3\0\2\3\3\0\17\3\14\0\6\3\1\122\13\3"+
    "\3\0\2\3\3\0\1\123\1\3\1\124\14\3\14\0"+
    "\22\3\3\0\2\3\3\0\3\3\1\125\13\3\14\0"+
    "\22\3\3\0\2\3\3\0\1\3\1\126\15\3\14\0"+
    "\22\3\3\0\2\3\3\0\4\3\1\127\12\3\14\0"+
    "\22\3\3\0\2\3\3\0\17\3\14\0\7\3\1\130"+
    "\12\3\3\0\2\3\3\0\7\3\1\131\7\3\14\0"+
    "\22\3\3\0\2\3\3\0\11\3\1\132\5\3\14\0"+
    "\22\3\3\0\2\3\3\0\14\3\1\133\2\3\14\0"+
    "\22\3\3\0\2\3\3\0\16\3\1\134\14\0\22\3"+
    "\3\0\2\3\3\0\16\3\1\135\14\0\22\3\3\0"+
    "\2\3\3\0\10\3\1\136\6\3\14\0\22\3\4\0"+
    "\1\114\34\0\1\137\26\0\2\3\3\0\10\3\1\140"+
    "\6\3\14\0\22\3\3\0\2\3\3\0\17\3\14\0"+
    "\3\3\1\141\16\3\3\0\2\3\3\0\17\3\14\0"+
    "\13\3\1\142\6\3\3\0\2\3\3\0\17\3\14\0"+
    "\20\3\1\143\1\3\3\0\2\3\3\0\17\3\14\0"+
    "\7\3\1\144\12\3\3\0\2\3\3\0\17\3\14\0"+
    "\1\145\21\3\3\0\2\3\3\0\4\3\1\132\12\3"+
    "\14\0\22\3\3\0\2\3\3\0\10\3\1\146\6\3"+
    "\14\0\22\3\3\0\2\3\3\0\10\3\1\147\6\3"+
    "\14\0\22\3\3\0\2\3\3\0\10\3\1\150\6\3"+
    "\14\0\22\3\3\0\2\3\3\0\3\3\1\151\13\3"+
    "\14\0\22\3\3\0\2\3\3\0\5\3\1\152\11\3"+
    "\14\0\22\3\3\0\2\3\3\0\10\3\1\153\6\3"+
    "\14\0\22\3\3\0\2\3\3\0\5\3\1\154\11\3"+
    "\14\0\22\3\3\0\2\3\3\0\11\3\1\155\5\3"+
    "\14\0\22\3\3\0\2\3\3\0\5\3\1\156\11\3"+
    "\14\0\22\3\3\0\2\3\3\0\17\3\14\0\1\3"+
    "\1\157\20\3\3\0\2\3\3\0\17\3\14\0\14\3"+
    "\1\160\5\3\3\0\2\3\3\0\17\3\14\0\1\3"+
    "\1\161\20\3\3\0\2\3\3\0\10\3\1\162\6\3"+
    "\14\0\22\3\3\0\2\3\3\0\4\3\1\163\3\3"+
    "\1\164\6\3\14\0\22\3\3\0\2\3\3\0\1\165"+
    "\16\3\14\0\22\3\3\0\2\3\3\0\17\3\14\0"+
    "\10\3\1\166\11\3\3\0\2\3\3\0\4\3\1\167"+
    "\12\3\14\0\22\3\3\0\2\3\3\0\10\3\1\170"+
    "\6\3\14\0\22\3\3\0\2\3\3\0\14\3\1\171"+
    "\2\3\14\0\22\3\3\0\2\3\3\0\17\3\14\0"+
    "\10\3\1\172\11\3\3\0\2\3\3\0\17\3\14\0"+
    "\4\3\1\173\15\3\3\0\2\3\3\0\17\3\14\0"+
    "\15\3\1\174\4\3\3\0\2\3\3\0\17\3\14\0"+
    "\14\3\1\175\5\3\3\0\2\3\3\0\11\3\1\176"+
    "\5\3\14\0\22\3\3\0\2\3\3\0\17\3\14\0"+
    "\10\3\1\177\11\3\3\0\2\3\3\0\4\3\1\200"+
    "\12\3\14\0\22\3\3\0\2\3\3\0\11\3\1\201"+
    "\5\3\14\0\22\3\3\0\2\3\3\0\4\3\1\202"+
    "\12\3\14\0\22\3\3\0\2\3\3\0\1\132\16\3"+
    "\14\0\22\3\3\0\2\3\3\0\3\3\1\154\13\3"+
    "\14\0\22\3\3\0\2\3\3\0\11\3\1\203\5\3"+
    "\14\0\22\3\3\0\2\3\3\0\17\3\14\0\16\3"+
    "\1\204\3\3\3\0\2\3\3\0\17\3\14\0\17\3"+
    "\1\205\2\3\3\0\2\3\3\0\3\3\1\206\13\3"+
    "\14\0\22\3\3\0\2\3\3\0\2\3\1\207\14\3"+
    "\14\0\22\3\3\0\2\3\3\0\10\3\1\210\6\3"+
    "\14\0\22\3\3\0\2\3\3\0\5\3\1\211\11\3"+
    "\14\0\22\3\3\0\2\3\3\0\1\3\1\212\15\3"+
    "\14\0\22\3\3\0\2\3\3\0\17\3\14\0\6\3"+
    "\1\213\13\3\3\0\2\3\3\0\17\3\14\0\15\3"+
    "\1\214\4\3\3\0\2\3\3\0\1\215\16\3\14\0"+
    "\22\3\3\0\2\3\3\0\3\3\1\216\13\3\14\0"+
    "\22\3\3\0\2\3\3\0\4\3\1\217\12\3\14\0"+
    "\22\3\3\0\2\3\3\0\17\3\14\0\10\3\1\220"+
    "\11\3\3\0\2\3\3\0\17\3\14\0\1\3\1\221"+
    "\20\3\3\0\2\3\3\0\17\3\14\0\4\3\1\222"+
    "\15\3\3\0\2\3\3\0\10\3\1\223\6\3\14\0"+
    "\22\3\3\0\2\3\3\0\1\224\16\3\14\0\22\3"+
    "\3\0\2\3\3\0\4\3\1\225\12\3\14\0\22\3"+
    "\3\0\2\3\3\0\17\3\14\0\2\3\1\226\17\3"+
    "\3\0\2\3\3\0\17\3\14\0\21\3\1\227\3\0"+
    "\2\3\3\0\4\3\1\230\12\3\14\0\22\3\3\0"+
    "\2\3\3\0\11\3\1\231\5\3\14\0\22\3\3\0"+
    "\2\3\3\0\17\3\14\0\17\3\1\232\2\3\3\0"+
    "\2\3\3\0\17\3\14\0\16\3\1\233\3\3\3\0"+
    "\2\3\3\0\5\3\1\234\11\3\14\0\22\3\3\0"+
    "\2\3\3\0\17\3\14\0\12\3\1\235\7\3\3\0"+
    "\2\3\3\0\17\3\14\0\12\3\1\236\7\3\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6413];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\15\1\1\11\1\1\5\11"+
    "\1\1\1\11\10\1\1\0\17\1\1\11\1\0\1\11"+
    "\1\0\1\11\22\1\1\0\22\1\1\11\77\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[158];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline = 1;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn = 1;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
   
 public String lexeme; 
 public int line;
 public int column;   


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 156) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 40: 
          { lexeme=yytext();line=yyline;column=yycolumn; return COMPILADORES;
          }
        case 41: break;
        case 5: 
          { /* ignore whitespace */
          }
        case 42: break;
        case 9: 
          { lexeme=yytext();line=yyline;column=yycolumn; return PONTO_VIRGULA;
          }
        case 43: break;
        case 27: 
          { lexeme=yytext();line=yyline;column=yycolumn; return PARA;
          }
        case 44: break;
        case 23: 
          { lexeme=yytext();line=yyline;column=yycolumn; return VAL_TEXTO;
          }
        case 45: break;
        case 25: 
          { lexeme=yytext();line=yyline;column=yycolumn; return POR;
          }
        case 46: break;
        case 19: 
          { lexeme=yytext();line=yyline;column=yycolumn; return EM;
          }
        case 47: break;
        case 6: 
          { lexeme=yytext();line=yyline;column=yycolumn; return OP_LOGICO;
          }
        case 48: break;
        case 31: 
          { lexeme=yytext();line=yyline;column=yycolumn; return BUSCAR;
          }
        case 49: break;
        case 8: 
          { lexeme=yytext();line=yyline;column=yycolumn; return ASPAS;
          }
        case 50: break;
        case 36: 
          { lexeme=yytext();line=yyline;column=yycolumn; return SUBSTITUIR;
          }
        case 51: break;
        case 14: 
          { lexeme=yytext();line=yyline;column=yycolumn; return ABRE_PARENTESES;
          }
        case 52: break;
        case 2: 
          { lexeme=yytext();line=yyline;column=yycolumn; return VAR;
          }
        case 53: break;
        case 15: 
          { lexeme=yytext();line=yyline;column=yycolumn; return FECHA_PARENTESES;
          }
        case 54: break;
        case 30: 
          { lexeme=yytext();line=yyline;column=yycolumn; return COND_SENAO;
          }
        case 55: break;
        case 11: 
          { lexeme=yytext();line=yyline;column=yycolumn; return FECHA_COLCHETES;
          }
        case 56: break;
        case 10: 
          { lexeme=yytext();line=yyline;column=yycolumn; return ABRE_COLCHETES;
          }
        case 57: break;
        case 1: 
          { lexeme=yytext() ;line=yyline;column=yycolumn; return ERRO;
          }
        case 58: break;
        case 34: 
          { lexeme=yytext();line=yyline;column=yycolumn; return ENQUANTO;
          }
        case 59: break;
        case 3: 
          { lexeme=yytext();line=yyline;column=yycolumn; return VAL_INTEIRO;
          }
        case 60: break;
        case 13: 
          { lexeme=yytext();line=yyline;column=yycolumn; return FECHA_CHAVES;
          }
        case 61: break;
        case 32: 
          { lexeme=yytext();line=yyline;column=yycolumn; return INICIO;
          }
        case 62: break;
        case 17: 
          { lexeme=yytext();line=yyline;column=yycolumn; return OP_RELACIONAL;
          }
        case 63: break;
        case 28: 
          { lexeme=yytext();line=yyline;column=yycolumn; return TIPO_VAR;
          }
        case 64: break;
        case 18: 
          { /* ignore comments */
          }
        case 65: break;
        case 22: 
          { lexeme=yytext();line=yyline;column=yycolumn; return OP_INCREMENTO;
          }
        case 66: break;
        case 21: 
          { lexeme=yytext();line=yyline;column=yycolumn; return COND_SE;
          }
        case 67: break;
        case 33: 
          { lexeme=yytext();line=yyline;column=yycolumn; return EXTRAIR;
          }
        case 68: break;
        case 4: 
          { /* ignore Line */
          }
        case 69: break;
        case 24: 
          { lexeme=yytext();line=yyline;column=yycolumn; return ATE;
          }
        case 70: break;
        case 37: 
          { lexeme=yytext();line=yyline;column=yycolumn; return CONCATENAR;
          }
        case 71: break;
        case 16: 
          { lexeme=yytext();line=yyline;column=yycolumn; return OP_ATRIBUICAO;
          }
        case 72: break;
        case 7: 
          { lexeme=yytext();line=yyline;column=yycolumn; return OP_ARITIMETICOS;
          }
        case 73: break;
        case 12: 
          { lexeme=yytext();line=yyline;column=yycolumn; return ABRE_CHAVES;
          }
        case 74: break;
        case 35: 
          { lexeme=yytext();line=yyline;column=yycolumn; return COMPARAR;
          }
        case 75: break;
        case 39: 
          { lexeme=yytext();line=yyline;column=yycolumn; return IFSULDEMINAS;
          }
        case 76: break;
        case 26: 
          { lexeme=yytext();line=yyline;column=yycolumn;  return FIM;
          }
        case 77: break;
        case 20: 
          { lexeme=yytext();line=yyline;column=yycolumn; return DE;
          }
        case 78: break;
        case 38: 
          { lexeme=yytext();line=yyline;column=yycolumn; return COMPRIMENTO;
          }
        case 79: break;
        case 29: 
          { lexeme=yytext();line=yyline;column=yycolumn; return VAL_BOOLEANO;
          }
        case 80: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
