
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jun 08 22:51:41 BRT 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Ponto_V = 28;
  public static final int T_dado = 4;
  public static final int Else = 7;
  public static final int For = 10;
  public static final int Numero = 30;
  public static final int Begin = 27;
  public static final int Divisao = 15;
  public static final int Paren_F = 22;
  public static final int Op_booleano = 20;
  public static final int ERROR = 31;
  public static final int Identificador = 29;
  public static final int Paren_A = 21;
  public static final int Colchete_F = 26;
  public static final int Resto = 13;
  public static final int Op_atribuicao = 18;
  public static final int Op_relacional = 17;
  public static final int Colchete_A = 25;
  public static final int cadeiraString = 5;
  public static final int Chave_F = 24;
  public static final int EOF = 0;
  public static final int Chave_A = 23;
  public static final int Op_incremento = 19;
  public static final int Multiplicacao = 14;
  public static final int If = 6;
  public static final int error = 1;
  public static final int Linha = 2;
  public static final int Aspas = 3;
  public static final int Op_logico = 16;
  public static final int Do = 8;
  public static final int Soma = 12;
  public static final int Igual = 11;
  public static final int While = 9;
}

